[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  CI = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API endpoint for Airtable integration
[[redirects]]
  from = "/api/airtable"
  to = "/.netlify/functions/airtable"
  status = 200

[[redirects]]
  from = "/api/airtable/test"
  to = "/.netlify/functions/airtable-test"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  functions = "netlify/functions"